name: ContohCI

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Skenario Test 1
      run: echo "Menjalankan Test 1"

    - name: Skenario Test 2
      run: echo "Menjalankan Test 2"

    - name: Skenario Test 3
      run: echo "Menjalankan Test 3"

  build_image:
    runs-on: ubuntu-latest

    steps:
    - name: Build image script
      run: |
        echo "membuat docker image ..."
        echo "tagging docker ..."

  push_image:
    runs-on: ubuntu-latest

    steps:
    - name: Push image script
      run: |
        echo "Login Docker Registry ..."
        echo "Push docker ke image registry"
